apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "haproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "haproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: sysctl-buddy
        image: alpine
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.core.somaxconn=32768
          sysctl -w net.ipv4.ip_local_port_range='1024 65535'
        securityContext:
          privileged: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: "/usr/local/etc/haproxy"
        - name: haproxy-secret
          mountPath: "/tmp/secrets"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: stats
          containerPort: 8100
          protocol: TCP
        resources:
            {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: haproxy-secret
        secret:
            secretName: haproxy-{{ .Values.global.environmentSuffix }}
            items:
            - key: bundle.pem
              path: bundle.pem
            - key: ca.pem
              path: ca.pem
            - key: dhparams.pem
              path: dhparams.pem
      - name: config-volume
        configMap:
            name: haproxy-config
            items:
            - key: haproxy.cfg
              path: haproxy.cfg
