apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
      global
        log stdout local0
        maxconn {{ .Values.maxconn | default 2048 }}
        nbproc {{ .Values.nbproc | default 1 }}

        ssl-dh-param-file /tmp/secrets/dhparams.pem
        ssl-default-server-options no-sslv3 no-tls-tickets
        ssl-default-bind-options no-sslv3 no-tls-tickets

        ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA
        ssl-default-server-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA

        resolvers k8s-dns
           parse-resolv-conf
           accepted_payload_size 8192 # allow larger DNS payloads

        defaults
                log     global
                mode    tcp
                option  httplog
                option  dontlognull
                option http-use-htx
                retries 3
                option redispatch
                maxconn {{ .Values.maxconn | default 2048 }}
                timeout connect 5s
                timeout client 120s
                timeout server 120s
                log-format '{"timestamp": %Ts,"https_status":%ST,"http_request":"%r","remote_addr":"%ci","bytes_read":%B,"upstream_addr":"%si","backend_name":"%b","retries":%rc,"bytes_uploaded":%U,"upstream_response_time":%Tr,"upstream_connect_time":%Tc,"session_duration":%Tt,"termination_state":"%ts"}'
        
        frontend tcp
           bind :80 accept-proxy
           mode http
           redirect scheme https code 301 if !{ ssl_fc }
        
        frontend tcp_ssl
           bind :443 accept-proxy ssl crt /tmp/secrets/bundle.pem
           mode http 
           acl is_stomp path_beg /stomp
           acl is_mqtt path_beg /ws
           use_backend stomp if is_stomp
           # HSTS (15768000 seconds = 6 months)
           #http-response set-header Strict-Transport-Security max-age=15768000
       
        backend stomp
              mode http 
              balance leastconn 
              server-template agentmq {{ .Values.stompReplicaCount}} agentmq-headless.{{ .Release.Namespace }}.svc.cluster.local:15674 send-proxy-v2-ssl-cn check inter 10s fall 6 resolvers k8s-dns init-addr none

        listen  stats
                bind :8100
                mode http
                http-request use-service prometheus-exporter if { path /metrics }
                stats enable
                stats uri /stats
                stats refresh 10s
