# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  rabbitmq-prometheus:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:

services:
  rabbitmq1: &rabbitmq
    # https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-prometheus/tags
    image: pivotalrabbitmq/rabbitmq-prometheus:3.8-2019.04.22
    networks:
      - "rabbitmq-prometheus"
    ports:
      - "15672:15672"
      - "15692:15692"
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-prometheus
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    # we want to simulate hitting thresholds
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"
  rabbitmq2:
    << : *rabbitmq
    hostname: rabbitmq2
    ports:
      - "25672:15672"
      - "25692:15692"
  rabbitmq3:
    << : *rabbitmq
    hostname: rabbitmq3
    ports:
      - "35672:15672"
      - "35692:15692"
  perf-test:
    # https://hub.docker.com/r/pivotalrabbitmq/perf-test/
    image: pivotalrabbitmq/perf-test:2.7.0
    networks:
      - "rabbitmq-prometheus"
    environment:
      URIS: "amqp://guest:guest@rabbitmq1:5672/%2f,amqp://guest:guest@rabbitmq2:5672/%2f,amqp://guest:guest@rabbitmq3:5672/%2f"
      PRODUCERS: 3
      CONSUMERS: 3
      RATE: 10
      CONFIRM: 1
      FLAG: mandatory
    entrypoint: []
    command: /bin/bash -c "while sleep 1; do nc -zv rabbitmq1 5672 && nc -zv rabbitmq2 5672 && nc -zv rabbitmq3 5672 && break; done && bin/runjava com.rabbitmq.perf.PerfTest"
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
  prometheus:
    # https://hub.docker.com/r/prom/prometheus/
    image: prom/prometheus:v2.9.0
    networks:
      - "rabbitmq-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    # https://hub.docker.com/r/grafana/grafana/
    image: grafana/grafana:6.1.3
    ports:
      - "3000:3000"
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards
