---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: agentmq-endpoint-reader
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: agentmq-endpoint-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agentmq-endpoint-reader

